@startuml sq-66-add-nhanvien
title Biểu đồ tuần tự - Thêm nhân viên
skinparam shadowing false
skinparam sequence {
  ArrowColor #444444
  LifeLineBorderColor #FF5E8E
  ParticipantBorderColor #FF5E8E
  ParticipantBackgroundColor #FFF0F3
}
actor "Nhân viên" as U
participant "admin/employees.php" as V
participant "EmployeeBLL" as B
participant "EmployeeDAL" as D
database "CSDL" as DB
U -> V : Nhập thông tin nhân viên mới
activate V
V -> B : create(data)
activate B
B -> B : Kiểm tra tính đúng đắn dữ liệu
alt Dữ liệu hợp lệ
  B -> D : create(data)
  D -> DB : INSERT nhân viên
  DB --> D : mã mới
  D --> B : mã mới
  B --> V : thành công
  V --> U : "Thêm nhân viên thành công"
else Dữ liệu không hợp lệ
  B --> V : lỗi
  V --> U : "Yêu cầu nhập đúng thông tin"
end
deactivate B
deactivate V

@enduml
