@startuml sq-65-manage-nhanvien
title Biểu đồ tuần tự - Quản lý nhân viên
skinparam shadowing false
skinparam sequence {
  ArrowColor #444444
  LifeLineBorderColor #FF5E8E
  ParticipantBorderColor #FF5E8E
  ParticipantBackgroundColor #FFF0F3
}
actor "Nhân viên" as U
participant "admin/employees.php" as V
participant "EmployeeBLL" as B
participant "EmployeeDAL" as D
database "CSDL" as DB
U -> V : Chọn chức năng quản lý nhân viên
activate V
V -> B : getAll()
activate B
B -> D : getAll()
D -> DB : SELECT danh sách nhân viên
DB --> D : dữ liệu
D --> B : danh sách
B --> V : danh sách
deactivate B
V --> U : Hiển thị danh sách nhân viên
deactivate V

@enduml
