@startuml uc-u04-dangnhap
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #FFF0F3
  BorderColor #FF5E8E
  ArrowColor #444444
}
title Use case chi tiết - Đăng nhập (UC04)
actor "Admin" as ACT0
actor "Khách hàng" as ACT1
rectangle "Đăng nhập" {
  usecase "Nhập thông tin đăng nhập" as U0
  usecase "Xác thực tài khoản" as U1
}
ACT0 -- U0
ACT0 -- U1
ACT1 -- U0
ACT1 -- U1
@enduml
